/**
 * 시드 룰셋 (초기 내장 UI 패턴 규칙)
 * 출처: Nielsen Norman Group(NN/g), Baymard Institute, Material Design 3, Apple HIG 등
 * 이 배열은 최초 실행 시 localStorage로 복사되며, 이후 앱은 localStorage 버전만 사용한다.
 * (즉, 이 파일을 직접 수정해도 이미 초기화된 브라우저에는 반영되지 않는다 — 설정 탭의
 *  "시드로 초기화"를 사용하거나 localStorage를 비워야 한다.)
 */
const SEED_RULESET = [
  // 1. 내비게이션/구조
  {
    id: "nav-gnb-count-01",
    category: "내비게이션/구조",
    condition: "GNB(전역 내비게이션) 메뉴 항목 개수 결정",
    recommendation: "5~7개 이내로 구성 (Hick's Law: 선택지가 많을수록 의사결정 시간 증가)",
    source: "Nielsen Norman Group",
    rationale: "선택지가 늘어날수록 사용자의 인지 부하와 의사결정 시간이 비례해서 증가한다",
    avoid_when: ["카테고리가 8개 이상인 경우 상위 카테고리로 그룹핑 필요"],
    implementation_notes: ["우선순위가 낮은 메뉴는 '더보기'로 묶기", "가장 많이 쓰는 메뉴를 좌측/상단에 배치"],
    created_by: "seed",
  },
  {
    id: "nav-lnb-vs-tab-01",
    category: "내비게이션/구조",
    condition: "동일 레벨 카테고리가 3~5개이고 콘텐츠 전환이 잦음",
    recommendation: "탭(Tab) 내비게이션",
    source: "Material Design 3",
    rationale: "탭은 같은 화면 내에서 콘텐츠를 빠르게 전환할 때 사용자의 위치 인지 부담이 적다",
    avoid_when: ["카테고리가 6개 이상인 경우 (가로 스크롤 탭이 되어 접근성 저하)", "카테고리 간 깊이(하위 메뉴)가 있는 경우"],
    implementation_notes: ["현재 탭은 색상+밑줄로 이중 강조", "탭 개수가 유동적이면 스와이프 가능한 스크롤 탭 고려"],
    created_by: "seed",
  },
  {
    id: "nav-breadcrumb-01",
    category: "내비게이션/구조",
    condition: "정보 구조가 3단계 이상의 계층을 가짐",
    recommendation: "브레드크럼(경로 표시) 노출",
    source: "Nielsen Norman Group",
    rationale: "사용자가 현재 위치와 상위 계층으로 돌아갈 경로를 인지하도록 도와 탐색 부담을 줄인다",
    avoid_when: ["계층이 2단계 이하로 얕은 경우 (오히려 불필요한 요소)", "모바일 좁은 화면에서 전체 경로가 너무 길 때는 축약 표시 필요"],
    implementation_notes: ["마지막 항목(현재 페이지)은 링크 비활성화", "구분자는 '>' 또는 '/' 사용"],
    created_by: "seed",
  },

  // 2. 리스트/콘텐츠 표시
  {
    id: "list-card-vs-list-01",
    category: "리스트/콘텐츠 표시",
    condition: "콘텐츠가 이미지/시각 정보 중심 (상품, 포트폴리오, 미디어)",
    recommendation: "카드형(Card) 레이아웃",
    source: "Nielsen Norman Group",
    rationale: "이미지가 큰 비중을 차지하는 콘텐츠는 카드형이 스캔 속도와 시각적 매력을 높인다",
    avoid_when: ["텍스트/수치 비교가 중요한 데이터 목록 (예: 정산 내역)"],
    implementation_notes: ["카드 내 정보 위계: 이미지 > 제목 > 부가정보 순", "카드 간 간격은 그리드 시스템에 맞춰 일정하게"],
    created_by: "seed",
  },
  {
    id: "list-table-01",
    category: "리스트/콘텐츠 표시",
    condition: "다속성 데이터를 비교/정렬해야 함 (예: 관리자 페이지, 주문 목록)",
    recommendation: "테이블형(Table) 레이아웃",
    source: "Nielsen Norman Group",
    rationale: "속성별 정렬과 스캔이 필요한 데이터는 표 형태가 비교 효율을 높인다",
    avoid_when: ["모바일 좁은 화면 (컬럼이 많으면 가로 스크롤 또는 카드형으로 반응형 전환 필요)"],
    implementation_notes: ["정렬 가능한 컬럼 헤더에는 화살표 아이콘 표시", "행 hover 시 배경색 강조"],
    created_by: "seed",
  },
  {
    id: "list-sort-position-01",
    category: "리스트/콘텐츠 표시",
    condition: "목록 화면에서 정렬 옵션 배치 위치",
    recommendation: "콘텐츠 영역 상단 우측, 결과 개수 표시와 나란히 배치",
    source: "Baymard Institute",
    rationale: "사용자는 결과 목록을 확인한 직후 정렬 기준을 찾는 시선 흐름을 보이며, 상단 우측이 관습적으로 학습된 위치다",
    avoid_when: [],
    implementation_notes: ["드롭다운 또는 칩 형태 모두 가능", "기본 정렬 기준(추천순/인기순 등)을 명확히 표기"],
    created_by: "seed",
  },

  // 3. 페이지네이션
  {
    id: "pagination-vs-infinite-01",
    category: "페이지네이션",
    condition: "사용자가 특정 목표(특정 상품/게시글)를 찾아 이동하는 목표 지향적 탐색",
    recommendation: "페이지네이션(번호형)",
    source: "Nielsen Norman Group",
    rationale: "페이지 번호는 위치 파악과 재방문(북마크, 뒤로가기)이 용이해 목표 지향적 탐색에 유리하다",
    avoid_when: ["피드형 콘텐츠 소비(발견형 탐색)인 경우"],
    implementation_notes: ["푸터 접근이 보장되어야 함", "현재 페이지/전체 페이지 수를 명확히 표기"],
    created_by: "seed",
  },
  {
    id: "pagination-vs-infinite-02",
    category: "페이지네이션",
    condition: "SNS 피드처럼 발견형·소비형 콘텐츠를 연속적으로 탐색",
    recommendation: "무한 스크롤",
    source: "Nielsen Norman Group",
    rationale: "탐색의 흐름을 끊지 않아 몰입감 있는 소비 경험을 제공한다",
    avoid_when: ["푸터 정보(약관, 문의 등)에 접근해야 하는 화면", "특정 항목으로 재방문/공유가 잦은 경우"],
    implementation_notes: ["'위로 가기' 버튼 필수 제공", "로딩 중임을 스켈레톤/스피너로 명확히 표시", "브라우저 뒤로가기 시 스크롤 위치 복원 고려"],
    created_by: "seed",
  },

  // 4. 검색
  {
    id: "search-position-01",
    category: "검색",
    condition: "검색이 서비스의 핵심 기능인 경우 (예: 이커머스, 콘텐츠 플랫폼)",
    recommendation: "데스크톱은 GNB 상단에 상시 노출된 검색창, 모바일은 아이콘 탭 시 전체 화면 검색으로 확장",
    source: "Baymard Institute",
    rationale: "검색을 자주 사용하는 서비스에서 검색창을 숨기면 발견성이 떨어져 이탈률이 증가한다",
    avoid_when: ["검색이 보조 기능인 경우 아이콘만으로 충분"],
    implementation_notes: ["플레이스홀더에 검색 예시 문구 노출", "검색창 너비는 최소 200px 이상 권장"],
    created_by: "seed",
  },
  {
    id: "search-autocomplete-01",
    category: "검색",
    condition: "검색어 입력 중 자동완성 제공 여부",
    recommendation: "2자 이상 입력 시 자동완성 노출, 최근 검색어와 인기 검색어를 구분해 표시",
    source: "Baymard Institute",
    rationale: "자동완성은 입력 노력을 줄이고 오탈자를 방지하며, 최근/인기 검색어 구분은 사용자의 의도(재검색 vs 탐색)를 지원한다",
    avoid_when: [],
    implementation_notes: ["최근 검색어는 개별 삭제 가능하게", "자동완성 항목은 최대 8~10개로 제한"],
    created_by: "seed",
  },
  {
    id: "search-no-result-01",
    category: "검색",
    condition: "검색 결과가 없는 경우의 화면 구성",
    recommendation: "검색어 철자 확인 안내 + 대안 검색어(유사어) 제안 + 인기 카테고리/상품 추천",
    source: "Baymard Institute",
    rationale: "결과 없음 화면에서 막다른 길처럼 느끼지 않도록 다음 행동을 제시해 이탈을 방지한다",
    avoid_when: [],
    implementation_notes: ["단순히 '검색 결과가 없습니다' 텍스트만 두지 말 것", "필터가 걸려 있었다면 필터 초기화 옵션 함께 제공"],
    created_by: "seed",
  },

  // 5. 필터
  {
    id: "filter-position-01",
    category: "필터",
    condition: "필터 UI 배치 위치 (반응형 기준)",
    recommendation: "데스크톱은 좌측 사이드바 상시 노출, 모바일/태블릿은 바텀시트 또는 풀스크린 모달",
    source: "Baymard Institute",
    rationale: "데스크톱은 화면 여유가 있어 필터와 결과를 동시에 비교하며 조정할 수 있어야 하고, 모바일은 화면 제약상 임시 오버레이가 적합하다",
    avoid_when: ["필터 항목이 1~2개로 매우 적은 경우 상단 드롭다운으로 대체 가능"],
    implementation_notes: ["모바일에서 '결과 보기' 버튼에 예상 결과 개수 실시간 표시", "필터 적용 중 로딩 상태 명확히 표시"],
    created_by: "seed",
  },
  {
    id: "filter-applied-display-01",
    category: "필터",
    condition: "적용된 필터를 사용자에게 어떻게 노출할지",
    recommendation: "결과 목록 상단에 칩(chip) 형태로 표시하고 개별 제거(x) 및 전체 초기화 버튼 제공",
    source: "Baymard Institute",
    rationale: "현재 적용된 조건을 한눈에 파악하고 개별 조정할 수 있어야 필터 사용에 대한 신뢰가 생긴다",
    avoid_when: [],
    implementation_notes: ["칩이 많아지면 줄바꿈 처리", "필터 패널 내부에도 선택 상태가 동기화되어야 함"],
    created_by: "seed",
  },

  // 6. FAQ/도움말
  {
    id: "faq-accordion-01",
    category: "FAQ/도움말",
    condition: "항목 10개 미만, 단일 카테고리",
    recommendation: "아코디언",
    source: "Nielsen Norman Group",
    rationale: "점진적 정보 노출로 인지 부하 감소",
    avoid_when: ["대부분의 콘텐츠에 접근이 필요한 경우", "콘텐츠가 다단계로 복잡한 경우"],
    implementation_notes: ["헤딩과 아이콘 모두 클릭 가능해야 함", "아코디언 중첩 금지"],
    created_by: "seed",
  },
  {
    id: "faq-help-center-01",
    category: "FAQ/도움말",
    condition: "FAQ 항목이 많고(수십 개 이상) 카테고리가 다양함",
    recommendation: "검색 가능한 별도 도움말 센터 페이지로 분리",
    source: "Nielsen Norman Group",
    rationale: "항목이 많아지면 단일 페이지 아코디언은 스캔 비용이 커지므로 카테고리 분류 + 검색이 필요하다",
    avoid_when: ["FAQ 항목이 20개 미만인 서비스 초기 단계"],
    implementation_notes: ["인기 질문 Top5를 최상단에 노출", "관련 질문 추천 기능 고려"],
    created_by: "seed",
  },
  {
    id: "faq-tab-01",
    category: "FAQ/도움말",
    condition: "FAQ가 서로 다른 대주제(예: 배송/결제/회원) 3~5개로 명확히 구분됨",
    recommendation: "탭으로 대주제를 구분한 뒤 각 탭 안에서 아코디언 사용",
    source: "Material Design 3",
    rationale: "대주제 구분이 명확할 때 탭은 카테고리 간 전환을, 아코디언은 세부 항목의 점진적 노출을 동시에 지원한다",
    avoid_when: ["대주제 구분이 모호하거나 항목 수가 매우 적은 경우"],
    implementation_notes: [],
    created_by: "seed",
  },

  // 7. 폼/입력
  {
    id: "form-validation-timing-01",
    category: "폼/입력",
    condition: "형식이 명확한 필드(이메일, 비밀번호, 전화번호)의 유효성 검사 시점",
    recommendation: "포커스 아웃(blur) 시 즉시 인라인 검사",
    source: "Nielsen Norman Group",
    rationale: "형식 오류는 즉시 피드백을 줘야 사용자가 제출 시점에 여러 오류를 한꺼번에 마주치지 않는다",
    avoid_when: ["타이핑 중(keystroke마다) 검사하면 미완성 입력에도 오류가 떠 불쾌감을 유발하므로 지양"],
    implementation_notes: ["입력 완료 후 성공 상태(체크 아이콘)도 함께 표시하면 신뢰도 상승"],
    created_by: "seed",
  },
  {
    id: "form-validation-timing-02",
    category: "폼/입력",
    condition: "서버 검증이 필요한 필드(아이디 중복확인, 쿠폰 코드)의 유효성 검사 시점",
    recommendation: "제출 시 또는 별도 '확인' 버튼 클릭 시 검사",
    source: "Nielsen Norman Group",
    rationale: "서버 호출 비용이 있는 검증은 매 입력마다 수행할 수 없으므로 명시적 트리거가 필요하다",
    avoid_when: [],
    implementation_notes: ["로딩 상태를 버튼에 스피너로 표시", "결과를 필드 하단에 성공/실패로 명확히 안내"],
    created_by: "seed",
  },
  {
    id: "form-required-marking-01",
    category: "폼/입력",
    condition: "필수/선택 입력 항목 표기 방식",
    recommendation: "필수 항목이 적으면 필수 항목에만 '*' 표시, 선택 항목이 적으면 선택 항목에 '(선택)' 표시",
    source: "Nielsen Norman Group",
    rationale: "전체 필드 중 소수인 쪽에만 라벨을 붙이는 것이 인지 효율이 높다",
    avoid_when: [],
    implementation_notes: ["'*' 표시의 의미를 폼 상단에 범례로 설명"],
    created_by: "seed",
  },
  {
    id: "form-step-vs-single-01",
    category: "폼/입력",
    condition: "입력 필드 개수가 많은 폼(예: 회원가입, 대출 신청)",
    recommendation: "단계형(멀티스텝) 폼 + 진행률 표시",
    source: "Baymard Institute",
    rationale: "긴 단일 폼은 완료까지 남은 노력이 가늠되지 않아 이탈률이 높으며, 단계형은 심리적 완료 부담을 낮춘다",
    avoid_when: ["필드가 5개 이하인 짧은 폼은 단일 폼이 더 빠르고 단순함"],
    implementation_notes: ["각 단계는 독립적으로 검증", "이전 단계로 돌아가도 입력값 유지"],
    created_by: "seed",
  },
  {
    id: "form-error-position-01",
    category: "폼/입력",
    condition: "에러 메시지 표시 위치와 내용",
    recommendation: "해당 입력 필드 바로 아래에, 무엇이 잘못되었고 어떻게 고칠지 구체적으로 명시",
    source: "Nielsen Norman Group",
    rationale: "에러 위치와 필드가 멀면 사용자가 원인을 찾는 데 시간이 걸리고, 모호한 메시지는 재시도를 방해한다",
    avoid_when: [],
    implementation_notes: ["'잘못된 입력입니다' 같은 모호한 문구 금지 — 예: '비밀번호는 8자 이상이어야 합니다'", "필드 테두리도 빨간색으로 함께 강조"],
    created_by: "seed",
  },

  // 8. 모달/오버레이
  {
    id: "modal-vs-bottomsheet-01",
    category: "모달/오버레이",
    condition: "짧은 확인/선택이 필요한 경우 (데스크톱 기준)",
    recommendation: "모달(Dialog)",
    source: "Material Design 3",
    rationale: "현재 컨텍스트를 유지하면서 짧은 의사결정을 처리하기에 적합하다",
    avoid_when: ["입력 항목이 많거나 여러 단계가 필요한 경우 (풀페이지 고려)"],
    implementation_notes: ["배경 딤(dim) 처리 및 ESC/바깥 클릭으로 닫기 지원", "포커스 트랩 적용 필수"],
    created_by: "seed",
  },
  {
    id: "modal-vs-bottomsheet-02",
    category: "모달/오버레이",
    condition: "모바일에서 단일 액션(공유, 옵션 선택 등)을 처리",
    recommendation: "바텀시트",
    source: "Material Design 3",
    rationale: "엄지 조작 범위 내에서 접근성이 좋고, 모바일 환경에서 관습적으로 학습된 패턴이다",
    avoid_when: ["복잡한 다단계 입력이 필요한 경우"],
    implementation_notes: ["드래그로 닫기 제스처 지원", "핸들바(drag indicator)를 상단에 표시"],
    created_by: "seed",
  },
  {
    id: "modal-destructive-confirm-01",
    category: "모달/오버레이",
    condition: "삭제 등 되돌릴 수 없는 파괴적 액션 실행 전",
    recommendation: "모달로 재확인하며, 버튼 레이블에 구체적 동작을 명시 (예: '삭제' 대신 '영구 삭제')",
    source: "Nielsen Norman Group",
    rationale: "모호한 '확인' 버튼은 실수를 유발하며, 구체적 동작 명시가 실수를 줄인다",
    avoid_when: ["즉시 되돌리기(undo)가 가능한 가벼운 액션은 확인 모달 없이 토스트+되돌리기로 대체 가능"],
    implementation_notes: ["파괴적 액션 버튼은 위험색(빨강)으로 시각적 구분"],
    created_by: "seed",
  },

  // 9. 상태 디자인
  {
    id: "state-empty-01",
    category: "상태 디자인",
    condition: "빈 상태(empty state) 화면 구성",
    recommendation: "왜 비어있는지 상황을 설명하고, 다음 행동을 유도하는 CTA를 함께 배치",
    source: "Nielsen Norman Group",
    rationale: "빈 화면만 노출하면 오류로 오인하거나 다음 행동을 몰라 이탈할 수 있다",
    avoid_when: [],
    implementation_notes: ["일러스트/아이콘으로 상황을 시각적으로 전달", "예: 장바구니 비어있음 → '상품 둘러보기' CTA"],
    created_by: "seed",
  },
  {
    id: "state-loading-01",
    category: "상태 디자인",
    condition: "로딩 상태 표현 방식 (스켈레톤 vs 스피너)",
    recommendation: "콘텐츠 구조를 예측 가능한 경우(리스트, 카드) 스켈레톤, 전체 화면 전환이나 구조를 알 수 없는 경우 스피너",
    source: "Nielsen Norman Group",
    rationale: "스켈레톤은 곧 나타날 콘텐츠의 레이아웃을 미리 보여줘 체감 대기시간을 줄인다",
    avoid_when: ["로딩이 200ms 미만으로 매우 짧으면 표시하지 않는 것이 깜빡임을 줄임"],
    implementation_notes: ["3초 이상 지속되는 로딩은 진행률 또는 안내 문구 추가 고려"],
    created_by: "seed",
  },
  {
    id: "state-error-01",
    category: "상태 디자인",
    condition: "에러 상태 화면 구성",
    recommendation: "무엇이 잘못됐는지 원인 + 해결 방법 + 재시도 버튼을 함께 제공",
    source: "Nielsen Norman Group",
    rationale: "원인과 해결책 없이 에러만 표시하면 사용자가 스스로 복구할 방법이 없어 이탈로 이어진다",
    avoid_when: [],
    implementation_notes: ["기술적 에러 코드는 숨기거나 '문의 시 참고' 용도로 하단에 작게 표기"],
    created_by: "seed",
  },

  // 10. 버튼/CTA
  {
    id: "button-hierarchy-01",
    category: "버튼/CTA",
    condition: "한 화면 내 여러 버튼의 위계 설정",
    recommendation: "화면(또는 섹션)당 주요(Primary) 버튼은 1개 원칙, 보조 액션은 Outline/Text 스타일로 구분",
    source: "Material Design 3",
    rationale: "동급으로 강조된 버튼이 여러 개면 사용자가 우선순위를 파악하지 못해 의사결정이 지연된다",
    avoid_when: [],
    implementation_notes: ["파괴적 액션(삭제 등)은 별도 색상(위험색)으로 구분"],
    created_by: "seed",
  },
  {
    id: "button-sticky-cta-01",
    category: "버튼/CTA",
    condition: "스크롤이 긴 페이지에서 핵심 전환 액션(구매, 신청 등) 배치",
    recommendation: "화면 하단 고정(sticky) CTA",
    source: "Baymard Institute",
    rationale: "사용자가 스크롤 중 언제든 핵심 액션에 접근할 수 있어야 전환 이탈을 줄인다",
    avoid_when: ["콘텐츠 종속적인 보조 액션(예: '이 리뷰 도움돼요')은 인라인 배치가 자연스러움"],
    implementation_notes: ["다른 sticky 요소(하단 탭바 등)와 겹치지 않도록 z-index/여백 조정 필요"],
    created_by: "seed",
  },

  // 11. 알림
  {
    id: "notification-toast-01",
    category: "알림",
    condition: "확인이 필요 없는 일시적 정보성 메시지 (저장 완료, 복사됨 등)",
    recommendation: "토스트(Toast)",
    source: "Material Design 3",
    rationale: "짧은 시간 자동으로 사라지며 사용자의 작업 흐름을 방해하지 않는다",
    avoid_when: ["사용자의 응답(확인/취소)이 필요한 경우 (모달 또는 배너로 대체)"],
    implementation_notes: ["3~5초 후 자동 소멸", "화면 하단 또는 상단 중앙에 배치, 여러 개 쌓일 경우 스택 처리"],
    created_by: "seed",
  },
  {
    id: "notification-banner-01",
    category: "알림",
    condition: "지속적인 주의가 필요한 시스템 상태 (네트워크 오류, 서비스 점검 등)",
    recommendation: "배너(Banner)",
    source: "Material Design 3",
    rationale: "사용자가 닫기 전까지 유지되어야 하는 정보는 자동 소멸되는 토스트보다 배너가 적합하다",
    avoid_when: [],
    implementation_notes: ["화면 상단에 고정, 닫기(X) 버튼 제공", "상태 심각도에 따라 색상 구분(정보/경고/오류)"],
    created_by: "seed",
  },
  {
    id: "notification-badge-01",
    category: "알림",
    condition: "읽지 않은 알림 개수나 상태를 표시",
    recommendation: "뱃지(Badge)를 아이콘에 결합해 표시하고 클릭 시 상세 목록으로 연결",
    source: "Apple Human Interface Guidelines",
    rationale: "숫자 뱃지는 처리해야 할 항목의 존재와 양을 즉각적으로 인지시킨다",
    avoid_when: ["개수가 매우 커지는 경우(예: 100 이상) 'N+' 형태로 축약 표기"],
    implementation_notes: [],
    created_by: "seed",
  },

  // 12. 온보딩
  {
    id: "onboarding-tour-vs-walkthrough-01",
    category: "온보딩",
    condition: "재방문이 잦고 UI가 비교적 익숙한 서비스에 신규 기능 소개",
    recommendation: "툴팁 투어 (스킵 가능)",
    source: "Nielsen Norman Group",
    rationale: "가볍게 넘길 수 있어 이미 서비스에 익숙한 사용자의 학습 피로를 줄인다",
    avoid_when: ["완전히 새로운 개념/패러다임을 처음 학습시켜야 하는 경우"],
    implementation_notes: ["'다시 보지 않기' 옵션 제공", "한 번에 3~5개 이내로 제한"],
    created_by: "seed",
  },
  {
    id: "onboarding-tour-vs-walkthrough-02",
    category: "온보딩",
    condition: "완전히 새로운 개념이나 복잡한 플로우를 처음 학습시켜야 함",
    recommendation: "모달 워크스루(단계별 설명 화면)",
    source: "Nielsen Norman Group",
    rationale: "충분한 설명 공간과 순차적 스토리텔링이 필요한 경우 모달 형태가 정보 전달에 유리하다",
    avoid_when: ["단순한 기능 추가는 과도한 온보딩이 오히려 피로감을 줌"],
    implementation_notes: ["항상 스킵 버튼 제공", "3~5단계 이내로 구성"],
    created_by: "seed",
  },
  {
    id: "onboarding-empty-state-guide-01",
    category: "온보딩",
    condition: "최초 진입 시 데이터가 없는 화면(빈 상태)에서의 온보딩",
    recommendation: "빈 화면 자체에 사용법 안내와 첫 액션 유도 CTA를 배치 (Empty State 가이드)",
    source: "Nielsen Norman Group",
    rationale: "별도 온보딩 오버레이 없이도 빈 상태에서 자연스럽게 다음 행동을 학습시킬 수 있다",
    avoid_when: [],
    implementation_notes: ["예: 할 일 앱 최초 진입 시 '첫 할 일을 추가해보세요' + 추가 버튼"],
    created_by: "seed",
  },

  // 13. 인증/가입
  {
    id: "auth-social-login-position-01",
    category: "인증/가입",
    condition: "소셜 로그인과 이메일 가입을 함께 제공할 때 배치",
    recommendation: "소셜 로그인 버튼을 이메일 가입 폼보다 상단에 배치, 3개 이내로 제한",
    source: "Baymard Institute",
    rationale: "소셜 로그인은 가입 마찰을 크게 줄이므로 우선 노출하며, 너무 많은 옵션은 선택 장애를 유발한다",
    avoid_when: [],
    implementation_notes: ["'또는' 구분선으로 이메일 가입과 시각적으로 분리"],
    created_by: "seed",
  },
  {
    id: "auth-password-reset-01",
    category: "인증/가입",
    condition: "비밀번호 재설정 플로우 설계",
    recommendation: "이메일로 재설정 링크 발송 방식을 기본으로 하고, 링크의 만료 시간(보통 1시간)을 명시",
    source: "Nielsen Norman Group",
    rationale: "명확한 만료 안내가 없으면 사용자가 링크 실패 원인을 알 수 없어 문의로 이어진다",
    avoid_when: [],
    implementation_notes: ["재발송 버튼에 재요청 대기시간(예: 60초) 표시"],
    created_by: "seed",
  },
  {
    id: "auth-signup-step-01",
    category: "인증/가입",
    condition: "회원가입 시 입력 필드가 많은 경우",
    recommendation: "진행률이 표시되는 단계형 가입 플로우",
    source: "Baymard Institute",
    rationale: "긴 단일 가입 폼은 이탈률이 높으며, 단계 분리는 완료까지의 심리적 거리를 줄인다",
    avoid_when: ["필수 필드가 3~4개 이하인 간단한 가입은 단일 폼이 더 빠름"],
    implementation_notes: [],
    created_by: "seed",
  },

  // 14. 프로세스형 화면 (금융/공공기관 신청·심사 플로우 등)
  {
    id: "process-step-indicator-01",
    category: "프로세스형 화면",
    condition: "신청/심사 등 여러 단계로 구성된 프로세스 화면",
    recommendation: "전체 단계 수와 현재 위치를 항상 노출하는 스텝 인디케이터, 이전 단계로 돌아가기 허용",
    source: "Nielsen Norman Group",
    rationale: "사용자가 얼마나 남았는지 알아야 완료 의지를 유지하며, 되돌아가기 제한은 불안감과 이탈을 유발한다",
    avoid_when: ["본인인증처럼 보안상 뒤로가기가 제한되어야 하는 단계는 명확히 안내 후 예외 처리"],
    implementation_notes: ["완료된 단계는 체크 아이콘으로 구분", "현재 단계는 강조색"],
    created_by: "seed",
  },
  {
    id: "process-terms-agreement-01",
    category: "프로세스형 화면",
    condition: "약관 동의 UI 구성 (금융/공공 서비스 등 다수 약관이 있는 경우)",
    recommendation: "전체 동의 체크박스 + 개별 항목 펼침 보기, 필수/선택 여부를 명확히 구분 표기",
    source: "전자상거래 등에서의 소비자보호에 관한 법률 실무 가이드 / Nielsen Norman Group",
    rationale: "전체 동의만 강제하면 개별 약관 확인권이 침해되며, 필수/선택 구분이 없으면 사용자가 선택권을 인지하지 못한다",
    avoid_when: [],
    implementation_notes: ["필수 약관 미동의 시 다음 단계 진행 버튼 비활성화 또는 안내 메시지", "각 약관은 새 창/펼침으로 전문 확인 가능해야 함"],
    created_by: "seed",
  },
  {
    id: "process-identity-verification-01",
    category: "프로세스형 화면",
    condition: "본인인증(휴대폰 인증 등) 단계 설계",
    recommendation: "인증 시작 전 예상 소요 시간을 안내하고, 실패 시 구체적 원인과 재시도 방법을 제공",
    source: "금융권 UX 가이드라인 일반 원칙 / Nielsen Norman Group",
    rationale: "인증 절차 중 이탈은 전환율에 직접적 영향을 주므로 불확실성을 최소화해야 한다",
    avoid_when: [],
    implementation_notes: ["인증 진행 중에는 뒤로가기/새로고침 시 경고 표시", "타임아웃 시간을 화면에 카운트다운으로 노출"],
    created_by: "seed",
  },

  // 15. 예외처리
  {
    id: "exception-network-error-01",
    category: "예외처리",
    condition: "네트워크 오류로 콘텐츠를 불러오지 못함",
    recommendation: "재시도 버튼과 함께 오프라인 여부를 안내",
    source: "Nielsen Norman Group",
    rationale: "네트워크 문제는 사용자 조작과 무관하므로 즉시 재시도할 수 있는 명확한 경로가 필요하다",
    avoid_when: [],
    implementation_notes: ["가능하면 온라인 복귀를 자동 감지해 재시도 유도"],
    created_by: "seed",
  },
  {
    id: "exception-no-permission-01",
    category: "예외처리",
    condition: "권한이 없는 리소스에 접근했을 때",
    recommendation: "왜 접근이 제한되는지 설명하고, 로그인/권한 요청 등 대안 행동을 제공",
    source: "Nielsen Norman Group",
    rationale: "이유 없는 차단은 사용자를 당황하게 하고 신뢰를 떨어뜨린다",
    avoid_when: [],
    implementation_notes: ["단순 404와 구분되는 403/권한 오류 전용 화면 권장"],
    created_by: "seed",
  },
  {
    id: "exception-no-data-01",
    category: "예외처리",
    condition: "필터/검색 조건에 맞는 데이터가 없는 경우 (빈 상태와 구분)",
    recommendation: "'조건에 맞는 결과가 없습니다' 안내와 함께 필터 초기화 옵션을 제공",
    source: "Baymard Institute",
    rationale: "완전히 비어있는 빈 상태와 조건부로 결과가 없는 상태는 원인이 다르므로 다른 안내와 해결책이 필요하다",
    avoid_when: [],
    implementation_notes: [],
    created_by: "seed",
  },
];
